[package]
name = "aisopod"
version.workspace = true
edition.workspace = true

[dependencies]
aisopod-shared = { path = "../aisopod-shared" }
aisopod-config = { path = "../aisopod-config" }
aisopod-provider = { path = "../aisopod-provider" }
aisopod-tools = { path = "../aisopod-tools" }
aisopod-session = { path = "../aisopod-session" }
aisopod-memory = { path = "../aisopod-memory" }
aisopod-agent = { path = "../aisopod-agent" }
aisopod-channel = { path = "../aisopod-channel" }
aisopod-plugin = { path = "../aisopod-plugin" }
aisopod-gateway = { path = "../aisopod-gateway" }
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
